name: samples

on:
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  samples:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: samples

    - name: Sample light
      uses: cicirello/user-statistician@v1
      with:
        colors: light
        image-file: images/light.svg
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Sample dark
      uses: cicirello/user-statistician@v1
      with:
        colors: dark
        image-file: images/dark.svg
        include-title: false
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Sample dark-dimmed
      uses: cicirello/user-statistician@v1
      with:
        colors: dark-dimmed
        image-file: images/dark-dimmed.svg
        custom-title: My GitHub Statistics
        hide-keys: joined, mostStarred, mostForked, followers, following, private
        max-languages: 100
        animated-language-chart: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
